//
//  Utility.h
//  MyCards
//
//  Created by diepth2 on 05/07/16.
//
//

#ifndef Image_h
#define Image_h


#define IMAGE_ON "on.png"
#define IMAGE_OFF "off.png"
#define IMAGE_ON "on.png"
#define IMAGE_OFF "off.png"
#define IMAGE_CLOSE "ic_button_close.png"
#define IMAGE_SPOT "null_bg.png"
#define IMAGE_BG_POPUP_SETTING "bg_cai_dat.png"
#define IMAGE_CONTENT_POPUP_SETTING "cai_dat.png"
#define IMAGE_POPUP_TLMN "bgr_popup_tlmn.png"
#define IMAGE_MENU "btn_menu.png"
#define BGR_LISTGAMES "bg_game.png"
#define ICON_BTN_THONGBAO "btn_iconthongbao.png"
#define ICON_FRINED "ban_be.png"
#define ICON_HELP "btn_iconhelp.png"
#define ICON_GIFTCODE "btn_icongiftcode.png"
#define ICON_SETTING "cat_dat.png"
#define ICON_NAPXU "nap_xu.png"
#define ICON_TOP "xep_hang.png"
#define ICON_TLMN "show_game/icon_tlmn.png"
#define ICON_XOC_DIA "show_game/xoc_dia.png"
#define ICON_BACK "BACK.png"
#define ICON_BACK_TLMN "btn_back_tlmn.png"
#define ICON_ROW_BACK "arrow_back.png"
#define ICON_ROW_NEXT "arrow_next.png"
#define ICON_PHONE "btn_phone.png"
#define ICON_MESSAGE_INBOX "btn_hopthu.png"
#define ICON_NEXT "NEXT.png"
#define ICON_XITO "show_game/xi_to.png"
#define ICON_EMAIL "EMAIL.png"
#define ICON_PHOM "show_game/phom.png"
#define ICON_TITLE_ROOM_PLAY_TLMN "ic_title_room_play_tlmn.png"
#define ICON_TITLE_ROOM_PLAY_TLMN_SOLO "ic_title_room_play_tlmn_solo.png"
#define ICON_TITLE_ROOM_PLAY_LIENG "ic_title_room_play_lieng.png"
#define ICON_TITLE_ROOM_PLAY_PHOM "ic_title_room_play_phom.png"
#define ICON_TITLE_ROOM_PLAY_BACAY "ic_title_room_play_bacay.png"
#define ICON_TITLE_ROOM_PLAY_MAUBINH "icon_title_room_mau_binh.png"
#define ICON_TITLE_ROOM_PLAY_XOCDIA "icon_title_room_xoc_dia.png"
#define ICON_BACAY "show_game/bacay.png"
#define ICON_MAUBINH "show_game/mau_binh.png"
#define ICON_TALA "show_game/ta_la.png"
#define ICON_SAM_2 "show_game/sam_2.png"
#define ICON_DOI_THUONG "DOI_THUONG.png"
#define ICON_CHOINGAY "choi_ngay.png"
#define BGR_UNDERLINE "unde_table.png"
#define ICON_XU "icon_xu.png"
#define ICON_CHAT "chat.png"
#define SPRITE_BK_XUKEN "sprite_hienthixuken.png"
#define SPRITE_THONGTIN "sprite_thongtin.png"
#define IMAGE_POPUP_CHAT "chat/bgr_popup_chat.png"
#define IMAGE_SOANTINNHAN "chat/sprite_soantinnhan.png"
#define IMAGE_CHAT_EMOTION "chat/icon_emotion.png"
#define IMAGE_CHAT_EMOTION_CLICKED "chat/icon_emotion_clicked.png"
#define IMAGE_CHAT_TMP_CLICKED "chat/icon_tmp_chat_clicked.png"
#define IMAGE_CHAT_TMP "chat/icon_tmp_chat.png"
#define IMAGE_CONTENT_CHAT "chat/bg_content.png"
#define IMAGE_SEND_MESSAGE "chat/btn_gui.png"
#define IMAGE_MESSAGE_TEMP_2 "chat/sprite_text_2.png"
#define IMAGE_MESSAGE_TEMP_3 "chat/sprite_text_3.png"
#define IMAGE_MESSAGE_TEMP_4 "chat/sprite_text_4.png"

//doi luat
#define BG_CHANGE_RULE "change_rule/bg_popup.png"
#define IC_CHECKBOX_CHANGERULE "change_rule/bg_checkbox.png"
#define BTN_CLICK_CHANGERULE "change_rule/btn_clicked.png"
#define IC_CHANGRULE_ARROW "change_rule/icon_arrow.png"

#define ICON_PHOM_ACTIVE "show_game/phom_active.png"
#define ICON_WHEEL_ACTIVE "show_game/wheel_active.png"
#define ICON_MAU_BINH_ACTIVE "show_game/mau_binh_active.png"
#define ICON_TLMN_ACTIVE "show_game/tlmn_active.png"
#define ICON_TLMN_SOLO_ACTIVE "show_game/tlmn_solo_active.png"
#define ICON_BACAY_ACTIVE "show_game/ba_cay_active.png"
#define ICON_XOC_DIA_ACTIVE "show_game/xoc_dia_active.png"
#define ICON_LIENG_ACTIVE "show_game/lieng_active.png"
#define ICON_XITO_ACTIVE "show_game/xi_to_active.png"

//icon deactive 
#define ICON_WHEEL_DEACTIVE "show_game/wheel_deactive.png"
#define ICON_PHOM_DEACTIVE "show_game/phom_deactive.png"
#define ICON_MAUBINH_DEACTIVE "show_game/mau_binh_deactive.png"
#define ICON_TLMN_DEACTIVE "show_game/tlmn_deactive.png"
#define ICON_TLMN_SOLO_DEACTIVE "show_game/tlmn_solo_deactive.png"
#define ICON_BACAY_DEACTIVE "show_game/ba_cay_deactive.png"
#define ICON_XOC_DIA_DEACTIVE "show_game/xoc_dia_deactive.png"
#define ICON_LIENG_DEACTIVE "show_game/lieng_deactive.png"
#define ICON_XITO_DEACTIVE "show_game/xi_to_deactive.png"
// popup tao ban
#define ICON_BTN_OK "tao_ban/btn_ok.png"
#define ICON_VIP "tao_ban/icon_vip.png"
#define POPUP_CREATE_ROOM "tao_ban/popup.png"
#define ICON_XU_DEACTIVE "tao_ban/bgr_xu_deactive.png"
#define ICON_XU_ACTIVE "tao_ban/bgr_xu_active.png"
#define ICON_KEN "sprite_ken.png"
#define SPRITE_XU "sprite_xu.png"
#define BGR_INPUT_NAME "tao_ban/bgr_input_name.png"
#define BGR_TABLE_ACTVE "tao_ban/table_active.png"
#define BGR_TABLE_DEACTVE "tao_ban/table_deactive.png"
//pop up nap the
#define LOGO_VIETTEL "doi_the/logo_viettel.png"
#define LOGO_MOBIFONE "doi_the/logo_mobifone.png"
#define LOGO_VINAPHONE "doi_the/logo_vinaphone.png"
#define LOGO_MEGACARD "doi_the/logo_megacard.png"
#define LOGO_VIETTEL_ACTIVE "doi_the/logo_viettel_active.png"
#define LOGO_MOBIFONE_ACTIVE "doi_the/logo_mobifone_active.png"
#define LOGO_VINAPHONE_ACTIVE "doi_the/logo_vinaphone_active.png"
#define LOGO_MEGACARD_ACTIVE "doi_the/logo_megacard_active.png"
#define BGR_DOITHE "doi_the/bgr_khungnap.png"
#define BGR_POPUP_DOITHE "bkg_popup_doithe.png"
#define BGR_INPUT_TEXT "doi_the/input_text.png"
#define BGR_INPUT_CAPTCHA "doi_the/bgr_capcha.png"
#define ICON_RELOAD_CAPTCHA "doi_the/icon_restart_captcha.png"
//pop up mua the
#define ITEM_10K "mua_the/10K.png"
#define ITEM_20K "mua_the/20K.png"
#define ITEM_50K "mua_the/50K.png"
#define ITEM_100K "mua_the/100K.png"
#define ITEM_200K "mua_the/200K.png"
#define ITEM_500K "mua_the/500K.png"
#define BGR_BUY_CARD "mua_the/bgr_buy_card.png"
#define BGR_POP_UP_BUY_CARD "mua_the/popup_buy_card.png"
#define BGR_TITLE_BUY_CARD "mua_the/title_buy_card.png"
//user info
#define ICON_PENCIL "user_info/btn_pencil.png"
#define IMAGE_POPUP_CHANGE_PHONE "user_info/popup_change_name.png"
#define IMAGE_POPUP_CHANGE_PASS "user_info/popup_change_pass.png"
#define BGR_INPUT_PASS "user_info/bgr_input_pass.png"
#define BGR_INPUT_PHONE "user_info/sprite_dienten.png"
#define ICON_LOCK "user_info/bk_iconlock.png"
#define BUTTON_EXIT "user_info/btn_exit.png"
#define BUTTON_SAVE "user_info/btn_save.png"
// friend
#define BGR_FRIEND "friend/bgr_friend.png"
#define BGR_FRIEND_LEFT "friend/bgr_friend_left.png"
#define BGR_FRIEND_RIGHT "friend/bgr_friend_right.png"
#define CIRCLE_AVATAR "friend/circle_avatar.png"
#define TAB_FRIEND_ACTIVE "friend/tab_friend_active.png"
#define TAB_FRIEND_UNACTIVE "friend/tab_friend_unactive.png"
#define TAB_ADD_FRIEND "friend/bgr_add_friend.png"
#define BTN_SEND_SMS "friend/btn_send_sms.png"
#define BTN_UNFRIEND "friend/btn_unfriend.png"
#define CIRCLE_AVATAR_LEFT "friend/circle_avatar_left.png"
#define CIRCLE_AVATAR_RIGHT "friend/circle_acvatar_right.png"
#define BGR_NUMBER_PLAY "friend/bgr_number_play.png"
#define ICON_FRIEND_XU "friend/icon_xu.png"
#define ICON_FRIEND_KEN "friend/icon_ken.png"
#define SPRITE_FRIEND "friend/sprite_banbe.png"
#define ICON_ADD_FRIEND "friend/icon_add_friend.png"

//xoc dia
#define IC_SONGUOIXEM               "xocdia/icon_nguoichoingoai.png"
#define XOCDIA_BTN_KHUNGCUOC        "xocdia/khung_cuoc.png"
#define XOCDIA_BTN_KHUNGCUOC_WIN    "xocdia/khung_cuoc_win.png"
#define XOCDIA_BTN_CUOC             "xocdia/bg_cuoc.png"
#define XOCDIA_BTN_CUOC_WIN         "xocdia/bg_cuoc_win.png"
#define XOCDIA_BTN_XINCAI           "xocdia/bg_xinlamnhacai.png"
#define XOCDIA_BTN_HANDLER          "xocdia/btn_handler.png"
#define XOCDIA_BTN_GAPDOI			"xocdia/btn_gapdoi.png"
#define XOCDIA_CHIP1                "xocdia/btn_chipx1.png"
#define XOCDIA_CHIP5                "xocdia/btn_chipx5.png"
#define XOCDIA_CHIP25               "xocdia/btn_chipx25.png"
#define XOCDIA_CHIP50               "xocdia/btn_chipx50.png"
#define XOCDIA_DATCHIP              "xocdia/bg_chip.png"
#define XOCDIA_CHIP1_ONBOARD        "xocdia/chip1.png"
#define XOCDIA_CHIP5_ONBOARD        "xocdia/chip5.png"
#define XOCDIA_CHIP25_ONBOARD       "xocdia/chip25.png"
#define XOCDIA_CHIP50_ONBOARD       "xocdia/chip50.png"
#define XOCDIA_BAT                  "xocdia/bk_bat.png"
#define XOCDIA_DIA                  "xocdia/bk_dia.png"
#define XOCDIA_NUT_DO               "xocdia/nut_do.png"
#define XOCDIA_NUT_TRANG            "xocdia/nut_trang.png"
#define XOCDIA_SPRITE_DO            "xocdia/sprite_le.png"
#define XOCDIA_SPRITE_TRANG         "xocdia/sprite_chan.png"
#define XOCDIA_CHIP1_CLICK          "xocdia/btn_chipx1_clicked.png"
#define XOCDIA_CHIP1_ROTATE         "xocdia/chipx1_rotated.png"
#define XOCDIA_CHIP5_CLICK          "xocdia/btn_chipx5_clicked.png"
#define XOCDIA_CHIP5_ROTATE         "xocdia/chipx5_roated.png"
#define XOCDIA_CHIP25_CLICK         "xocdia/btn_chipx25_clicked.png"
#define XOCDIA_CHIP25_ROTATE        "xocdia/chipx25_rotated.png"
#define XOCDIA_CHIP50_CLICK         "xocdia/btn_chipx50_clicked.png"
#define XOCDIA_CHIP50_ROTATE        "xocdia/btn_chipx50_rotated.png"
#define XOCDIA_TOTAL_CHANLE         "xocdia/bg_left_total_chanle.png"
#define XOCDIA_THONGKE_CHANLE       "xocdia/bg_thongke_chanle.png"
#define XOCDIA_BG_4TRANG            "xocdia/bg_4trang.png"
#define XOCDIA_BG_3TRANG            "xocdia/bg_3trang.png"
#define XOCDIA_BG_1TRANG            "xocdia/bg_1trang.png"
#define XOCDIA_BG_0TRANG            "xocdia/bg_0trang.png"
#define XOCDIA_NOTIFY				"xocdia/bg_notify.png"
#define XOCDIA_SELL_SMALL           "xocdia/smallSell.png"
#define XOCDIA_SELL_NORMAL          "xocdia/sell.png"
#define XOCDIA_BUY_SMALL            "xocdia/smallBuy.png"
#define XOCDIA_BUY_NORMAL           "xocdia/buy.png"

//mail
#define MAIL_CELL_BACKGROUND        "mail/sprite_background.png"
#define MAIL_ICON_MAIL              "mail/sprite_email.png"
#define MAIL_SPRITE_CONTENT         "mail/sprite_noidung.png"
#define MAIL_THUNG_RAC              "mail/btn_thungrac.png"
#define MAIL_DOC_NHAN               "mail/btn_doc.png"
#define MAIL_RD_ICON_MAIL           "mail/sprite_da_doc_email.png"
#define MAIL_RD_SPRITE_CONTENT      "mail/sprite_da_doc_noidung.png"
#define MAIL_RD_THUNG_RAC           "mail/btn_da_doc_thungrac.png"
#define MAIL_RD_DOC_NHAN            "mail/btn_da_doc.png"
#define MAIL_BG_DOC_MAIL            "mail/sprite_docemail.png"
#define MAIL_LINE_TITLE             "mail/sprite_line_title.png"
#define MAIL_LINE_CONTENT           "mail/sprite_line_content.png"

#define BGR_RESET_PASS ""

//level up
#define BG_LEVELUP					"level_up/bg_level.png"


#endif /* Utility_h */
