//
//  LocalString.h
//  BigKen
//
//  Created by Hoàng Bắc Phùng on 10/22/16.
//
//

#ifndef LocalString_h
#define LocalString_h

#define INVALID_USERNAME            "Tên đăng nhập từ 3 đến 12 ký tự"
#define BLANK_USERNAME              "Vui lòng nhập vào ô trống"
#define BLANK_SECURITY              "Vui lòng nhập mã bảo mật"
#define BLANK_RESECURITY            "Vui lòng nhập lại mã bảo mật"
#define INVALID_MAXLENGTH_SECURITY  "Mã bảo mật từ 6 đến 12 kí tự"
#define SECURITY_NOT_MATCH          "Xác nhận mã bảo mật không chính xác!"
#define SECURITY_NOT_CHANGE         "Mã bảo mật mới không được trùng với mã bảo mật cũ"
#define INVALID_PASSWORD            "Mật khẩu từ 6 đến 12 ký tự"
#define INVALID_SERIA               "Seria hoặc Mã thẻ không đúng"
#define PASSWORD_NOT_MATCH          "Mật khẩu xác nhận không chính xác!"
#define PASSWORD_NOT_CHANGE         "Mật khẩu mới không được trùng với mật khẩu cũ"
#define BLANK_FILES                 "Vui lòng nhập đầy đủ dữ liệu"
#define MAIL_FOMAT                  " - Còn lại "
#define MAIL_TXT_NO_EXPIRED         " - Vô hạn"
#define MAIL_TXT_READ               "Đọc"
#define MAIL_TXT_RECV               "Nhận"
#define MAIL_TXT_HOME               "Hòm thư"
#define TEXT_CONFIRM                "Bạn có chắc chắn muốn thực hiện không?"
#define LS_DOITHUONG_TXT_PHATSINH   "Phát sinh"
#define LS_DOITHUONG_TXT_SODU       "Số dư"
#define LS_DOITHUONG_TXT_CONTENT    "Mô tả"
#define LS_DOITHUONG_TXT_TIME       "Thời gian"
#define LS_NAPXU_TXT_XUNAP          "Ken nạp"
#define LS_NAPKEN_TXT_XUDOI         "Số Ken đổi"
#define LS_NAPKEN_TXT_KENNHAN       "Số Xu nhận"
#define CHANGE_PASSWORD             "Đổi mật khẩu"
#define TXT_ADD_FRIEND              "Thêm bạn bè"
#define TXT_REMOVE_FRIEND           "Hủy kết bạn"
#define TXT_ACCEPT_FRIEND           "Chấp nhận kết bạn"
#define TXT_DENY_FRIEND             "Từ chối lời mời"
#define TXT_XOCDIA_XINCAI           "Xin làm cái"
#define TXT_XOCDIA_HUYCAI           "huỷ làm cái"
#define TEXT_LIST_EMPTY             "Danh sách trống"
#define CONTENT_MESSAGE_CHAT        "Nhập nội dung chat"
#define SEND_CHAT                   "Gửi"
#define MSG_CHAT_TEMP1              "Chào nhé ! mình out"
#define MSG_CHAT_TEMP2              "Đánh nhanh lên"
#define MSG_CHAT_TEMP3              "Bài đẹp quá"
#define MSG_CHAT_TEMP4              "Bài xấu VL"
#define MSG_CHAT_TEMP5              "Bài xấu quá"
#define MSG_CHAT_TEMP6              "chào cả nhà AHI"
#define CR_ROOM_BTN_OK              "OK"
#define CR_ROOM_SELECT              "Chọn"
#define CR_ROOM_INPUT_PASSWORD      "   Nhập mật khẩu"
#define CR_ROOM_INPUT_ROOMNAME      "   Nhập tên phòng"
#define CR_ROOM_ROOMNAME            "Tên phòng"
#define CR_ROOM_PASSWORD            "Mật khẩu"
#define TXT_LOGIN_BTN_LOGIN         "Đăng nhập"
#define TXT_LOGIN_BTN_REGISTER      "Đăng kí"
#define TXT_LOGIN_BTN_PLAYNOW       "Chơi thử"
#define TXT_LOGIN_BTN_FACEBOOK      "Đăng nhập bằng facebook"
#define TXT_REGISTER_LABEL_NOTIFY   "Nhập số điện thoại để nhận đổi thưởng"
#define TXT_CONNECT                 "Kết nối"
#define TXT_RECONNECT_MESSAGE       "Lỗi kết nối máy chủ, vui lòng thử lại."
#define TXT_OK                      "OK"
#define CELL_STATUS_PLAYING         "Đang chiến"
#define CELL_STATUS_MIS_SLOT        "Thiếu chân"
#define TABLE_TXT_SOBAN             "Số bàn"
#define TABLE_TXT_MUCCUOC           "Mức cược"
#define TABLE_TXT_SONGUOICHOI       "Số người chơi"
#define TABLE_TXT_TOITHIEU          "Tối thiểu"
#define TABLE_TXT_TRANGTHAI         "Trạng thái"
#define TEXT_SHOWGAME_HELLO         "Chào mừng bạn đã đến với Game Bài Đổi Thưởng BigKen Online !"
#define MSG_MAINTAIN                "Hệ thống đang bảo trì, vui lòng thử lại"
#define TXT_GOPGA                   "Góp Gà"
#define MSG_CONFIRM_BET_BARIER      "Người chơi %s muốn đánh biên số tiền %lld %s, bạn có muốn thử sức không?"
#define TITLE_POPUP_CONFIRM         "Xác nhận"
#define MSG_SELL_CHUONG             "Bạn là chương mới, bạn có muốn bán chương không?"
#define MSG_BUY_CHUONG              "Người cầm chương muốn bán chương cho bạn, bạn có muốn nhận chương không?"
#define TXT_BTN_START_MATCH         "Bắt đầu"
#define TXT_BTN_FINISH              "XONG"
#define TXT_ENOUGH_PLAYER           "Cần ít nhất 2 người chơi để bắt đầu ván chơi"
#define TXT_TITLE_GAME_TLMN         "TLMN"
#define TXT_TITLE_GAME_BACAY        "BA CÂY"
#define TXT_TITLE_GAME_PHOM         "PHỎM"
#define TXT_TITLE_GAME_XOCDIA       "CHẴN LẺ"
#define TXT_TITLE_GAME_MAUBINH      "MẬU BINH"
#define TXT_TITLE_GAME_TLMN_SOLO    "TLMN SOLO"
#define TXT_TITLE_GAME_TLMN_LIENG   "LIÊNG"
#define TEXT_NOTIFY_FUNCTION_FUTURE "Chức năng sắp ra mắt"
#define XOCDIA_TEXT_CHAN            "CHẴN "
#define XOCDIA_TEXT_LE              "LẺ "
#define NOT_ENOUGH_MONEY            "Bạn không đủ tiền để chọn mức cược này"
#define DENIED_BET                  "Vui lòng chờ giây lát đến lúc đặt cửa"
#define ME							"Tôi"
#define TXT_CHANGERULE_FIRST_TURN	"Nhất đánh trước"
#define TXT_CHANGERULE_RANDOM_TURN  "Ngẫu nhiên người đánh trước"
#define TXT_CHANGERULE_SHOW_CARD	"Hiện số lá bài còn lại"
#define TXT_CHANGERULE_HIDDEN_CARD	"Ẩn số lá bài còn lại"
#define TXT_CHANGERULE				"Luật chơi:"
#define TXT_LIST_OWNER				"DS LÀM CÁI"
#define TXT_SOCDIA_WATING_NEW_GAME	"Vui lòng đợi ván mới nhé!"
#define TXT_XOCDIA_REFUND           "Nhà cái hoàn %d tiền cân cửa"
#define TXT_XOCDIA_DENIED           "Nhà cái ngừng nhận cửa"
#define TXT_XOCDIA_SELL_GATE        "Nhà cái bán cửa"

#define TXT_INVITE                  "Người chơi %s mời bạn chơi game %s tại phòng %s bàn %d với mức cược %d %s"

#define TXT_LEVEUP					"LEVEL UP"
#define TXT_REGISTER_EXITROOM		"Bạn đã đăng ký rời phòng sau khi hết ván!"
#define TXT_CANCEL_EXITROOM			"Bạn đã hủy đăng ký rời phòng!"
#define TXT_DOITHE_DENIED_FEATURE   "Tài khoản của bạn không thể thực hiện được chức năng này, liên hệ quản trị viên để được hỗ trợ!"
#define TXT_CANCEL_EXCHANGE_XU      "XU không thể đổi thưởng và đổi ngược lại sang KEN"
#endif /* LocalString_h */
