// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: initialize.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "initialize.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace {

const ::google::protobuf::Descriptor* BINInitializeRequest_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  BINInitializeRequest_reflection_ = NULL;
const ::google::protobuf::Descriptor* BINInitializeResponse_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  BINInitializeResponse_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_initialize_2eproto() {
  protobuf_AddDesc_initialize_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "initialize.proto");
  GOOGLE_CHECK(file != NULL);
  BINInitializeRequest_descriptor_ = file->message_type(0);
  static const int BINInitializeRequest_offsets_[7] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(BINInitializeRequest, cp_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(BINInitializeRequest, appversion_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(BINInitializeRequest, deviceid_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(BINInitializeRequest, deviceinfo_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(BINInitializeRequest, country_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(BINInitializeRequest, language_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(BINInitializeRequest, pakagename_),
  };
  BINInitializeRequest_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      BINInitializeRequest_descriptor_,
      BINInitializeRequest::default_instance_,
      BINInitializeRequest_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(BINInitializeRequest, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(BINInitializeRequest, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(BINInitializeRequest));
  BINInitializeResponse_descriptor_ = file->message_type(1);
  static const int BINInitializeResponse_offsets_[20] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(BINInitializeResponse, responsecode_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(BINInitializeResponse, message_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(BINInitializeResponse, currentappversion_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(BINInitializeResponse, downloadurl_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(BINInitializeResponse, cashcurrency_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(BINInitializeResponse, goldcurrency_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(BINInitializeResponse, forceupdate_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(BINInitializeResponse, enablequickplay_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(BINInitializeResponse, enablecashsystem_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(BINInitializeResponse, enablepurchasecash_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(BINInitializeResponse, enabletopup_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(BINInitializeResponse, enablecashtogold_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(BINInitializeResponse, enablecashtransfer_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(BINInitializeResponse, enablegiftcode_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(BINInitializeResponse, cashtogoldratio_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(BINInitializeResponse, hotlines_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(BINInitializeResponse, fanpageurl_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(BINInitializeResponse, websiteurl_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(BINInitializeResponse, enablegameids_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(BINInitializeResponse, resetpwsmssyntax_),
  };
  BINInitializeResponse_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      BINInitializeResponse_descriptor_,
      BINInitializeResponse::default_instance_,
      BINInitializeResponse_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(BINInitializeResponse, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(BINInitializeResponse, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(BINInitializeResponse));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_initialize_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    BINInitializeRequest_descriptor_, &BINInitializeRequest::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    BINInitializeResponse_descriptor_, &BINInitializeResponse::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_initialize_2eproto() {
  delete BINInitializeRequest::default_instance_;
  delete BINInitializeRequest_reflection_;
  delete BINInitializeResponse::default_instance_;
  delete BINInitializeResponse_reflection_;
}

void protobuf_AddDesc_initialize_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\020initialize.proto\"\223\001\n\024BINInitializeRequ"
    "est\022\n\n\002cp\030\001 \002(\t\022\022\n\nappVersion\030\002 \002(\t\022\020\n\010d"
    "eviceId\030\003 \001(\t\022\022\n\ndeviceInfo\030\004 \001(\t\022\017\n\007cou"
    "ntry\030\005 \001(\t\022\020\n\010language\030\006 \001(\t\022\022\n\npakageNa"
    "me\030\007 \001(\t\"\345\003\n\025BINInitializeResponse\022\024\n\014re"
    "sponseCode\030\001 \002(\010\022\017\n\007message\030\002 \001(\t\022\031\n\021cur"
    "rentAppVersion\030\003 \001(\t\022\023\n\013downloadUrl\030\004 \001("
    "\t\022\024\n\014cashCurrency\030\005 \001(\t\022\024\n\014goldCurrency\030"
    "\006 \001(\t\022\023\n\013forceUpdate\030\007 \001(\010\022\027\n\017enableQuic"
    "kPlay\030\010 \001(\010\022\030\n\020enableCashSystem\030\t \001(\010\022\032\n"
    "\022enablePurchaseCash\030\n \001(\010\022\023\n\013enableTopup"
    "\030\013 \001(\010\022\030\n\020enableCashToGold\030\014 \001(\010\022\032\n\022enab"
    "leCashTransfer\030\r \001(\010\022\026\n\016enableGiftCode\030\016"
    " \001(\010\022\027\n\017cashToGoldRatio\030\017 \001(\005\022\020\n\010hotline"
    "s\030\020 \003(\t\022\022\n\nfanpageUrl\030\021 \001(\t\022\022\n\nwebsiteUr"
    "l\030\022 \001(\t\022\025\n\renableGameIds\030\023 \003(\005\022\030\n\020resetP"
    "wSmsSyntax\030\024 \001(\tB\036\n\034com.mi.game.network."
    "data.bin", 688);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "initialize.proto", &protobuf_RegisterTypes);
  BINInitializeRequest::default_instance_ = new BINInitializeRequest();
  BINInitializeResponse::default_instance_ = new BINInitializeResponse();
  BINInitializeRequest::default_instance_->InitAsDefaultInstance();
  BINInitializeResponse::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_initialize_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_initialize_2eproto {
  StaticDescriptorInitializer_initialize_2eproto() {
    protobuf_AddDesc_initialize_2eproto();
  }
} static_descriptor_initializer_initialize_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int BINInitializeRequest::kCpFieldNumber;
const int BINInitializeRequest::kAppVersionFieldNumber;
const int BINInitializeRequest::kDeviceIdFieldNumber;
const int BINInitializeRequest::kDeviceInfoFieldNumber;
const int BINInitializeRequest::kCountryFieldNumber;
const int BINInitializeRequest::kLanguageFieldNumber;
const int BINInitializeRequest::kPakageNameFieldNumber;
#endif  // !_MSC_VER

BINInitializeRequest::BINInitializeRequest()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void BINInitializeRequest::InitAsDefaultInstance() {
}

BINInitializeRequest::BINInitializeRequest(const BINInitializeRequest& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void BINInitializeRequest::SharedCtor() {
  _cached_size_ = 0;
  cp_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  appversion_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  deviceid_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  deviceinfo_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  country_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  language_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  pakagename_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

BINInitializeRequest::~BINInitializeRequest() {
  SharedDtor();
}

void BINInitializeRequest::SharedDtor() {
  if (cp_ != &::google::protobuf::internal::kEmptyString) {
    delete cp_;
  }
  if (appversion_ != &::google::protobuf::internal::kEmptyString) {
    delete appversion_;
  }
  if (deviceid_ != &::google::protobuf::internal::kEmptyString) {
    delete deviceid_;
  }
  if (deviceinfo_ != &::google::protobuf::internal::kEmptyString) {
    delete deviceinfo_;
  }
  if (country_ != &::google::protobuf::internal::kEmptyString) {
    delete country_;
  }
  if (language_ != &::google::protobuf::internal::kEmptyString) {
    delete language_;
  }
  if (pakagename_ != &::google::protobuf::internal::kEmptyString) {
    delete pakagename_;
  }
  if (this != default_instance_) {
  }
}

void BINInitializeRequest::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* BINInitializeRequest::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return BINInitializeRequest_descriptor_;
}

const BINInitializeRequest& BINInitializeRequest::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_initialize_2eproto();
  return *default_instance_;
}

BINInitializeRequest* BINInitializeRequest::default_instance_ = NULL;

BINInitializeRequest* BINInitializeRequest::New() const {
  return new BINInitializeRequest;
}

void BINInitializeRequest::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (has_cp()) {
      if (cp_ != &::google::protobuf::internal::kEmptyString) {
        cp_->clear();
      }
    }
    if (has_appversion()) {
      if (appversion_ != &::google::protobuf::internal::kEmptyString) {
        appversion_->clear();
      }
    }
    if (has_deviceid()) {
      if (deviceid_ != &::google::protobuf::internal::kEmptyString) {
        deviceid_->clear();
      }
    }
    if (has_deviceinfo()) {
      if (deviceinfo_ != &::google::protobuf::internal::kEmptyString) {
        deviceinfo_->clear();
      }
    }
    if (has_country()) {
      if (country_ != &::google::protobuf::internal::kEmptyString) {
        country_->clear();
      }
    }
    if (has_language()) {
      if (language_ != &::google::protobuf::internal::kEmptyString) {
        language_->clear();
      }
    }
    if (has_pakagename()) {
      if (pakagename_ != &::google::protobuf::internal::kEmptyString) {
        pakagename_->clear();
      }
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool BINInitializeRequest::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required string cp = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_cp()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->cp().data(), this->cp().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(18)) goto parse_appVersion;
        break;
      }

      // required string appVersion = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_appVersion:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_appversion()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->appversion().data(), this->appversion().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(26)) goto parse_deviceId;
        break;
      }

      // optional string deviceId = 3;
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_deviceId:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_deviceid()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->deviceid().data(), this->deviceid().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(34)) goto parse_deviceInfo;
        break;
      }

      // optional string deviceInfo = 4;
      case 4: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_deviceInfo:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_deviceinfo()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->deviceinfo().data(), this->deviceinfo().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(42)) goto parse_country;
        break;
      }

      // optional string country = 5;
      case 5: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_country:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_country()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->country().data(), this->country().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(50)) goto parse_language;
        break;
      }

      // optional string language = 6;
      case 6: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_language:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_language()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->language().data(), this->language().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(58)) goto parse_pakageName;
        break;
      }

      // optional string pakageName = 7;
      case 7: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_pakageName:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_pakagename()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->pakagename().data(), this->pakagename().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void BINInitializeRequest::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required string cp = 1;
  if (has_cp()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->cp().data(), this->cp().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      1, this->cp(), output);
  }

  // required string appVersion = 2;
  if (has_appversion()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->appversion().data(), this->appversion().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      2, this->appversion(), output);
  }

  // optional string deviceId = 3;
  if (has_deviceid()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->deviceid().data(), this->deviceid().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      3, this->deviceid(), output);
  }

  // optional string deviceInfo = 4;
  if (has_deviceinfo()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->deviceinfo().data(), this->deviceinfo().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      4, this->deviceinfo(), output);
  }

  // optional string country = 5;
  if (has_country()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->country().data(), this->country().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      5, this->country(), output);
  }

  // optional string language = 6;
  if (has_language()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->language().data(), this->language().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      6, this->language(), output);
  }

  // optional string pakageName = 7;
  if (has_pakagename()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->pakagename().data(), this->pakagename().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      7, this->pakagename(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* BINInitializeRequest::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required string cp = 1;
  if (has_cp()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->cp().data(), this->cp().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->cp(), target);
  }

  // required string appVersion = 2;
  if (has_appversion()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->appversion().data(), this->appversion().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->appversion(), target);
  }

  // optional string deviceId = 3;
  if (has_deviceid()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->deviceid().data(), this->deviceid().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->deviceid(), target);
  }

  // optional string deviceInfo = 4;
  if (has_deviceinfo()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->deviceinfo().data(), this->deviceinfo().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        4, this->deviceinfo(), target);
  }

  // optional string country = 5;
  if (has_country()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->country().data(), this->country().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        5, this->country(), target);
  }

  // optional string language = 6;
  if (has_language()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->language().data(), this->language().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        6, this->language(), target);
  }

  // optional string pakageName = 7;
  if (has_pakagename()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->pakagename().data(), this->pakagename().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        7, this->pakagename(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int BINInitializeRequest::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required string cp = 1;
    if (has_cp()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->cp());
    }

    // required string appVersion = 2;
    if (has_appversion()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->appversion());
    }

    // optional string deviceId = 3;
    if (has_deviceid()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->deviceid());
    }

    // optional string deviceInfo = 4;
    if (has_deviceinfo()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->deviceinfo());
    }

    // optional string country = 5;
    if (has_country()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->country());
    }

    // optional string language = 6;
    if (has_language()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->language());
    }

    // optional string pakageName = 7;
    if (has_pakagename()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->pakagename());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void BINInitializeRequest::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const BINInitializeRequest* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const BINInitializeRequest*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void BINInitializeRequest::MergeFrom(const BINInitializeRequest& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_cp()) {
      set_cp(from.cp());
    }
    if (from.has_appversion()) {
      set_appversion(from.appversion());
    }
    if (from.has_deviceid()) {
      set_deviceid(from.deviceid());
    }
    if (from.has_deviceinfo()) {
      set_deviceinfo(from.deviceinfo());
    }
    if (from.has_country()) {
      set_country(from.country());
    }
    if (from.has_language()) {
      set_language(from.language());
    }
    if (from.has_pakagename()) {
      set_pakagename(from.pakagename());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void BINInitializeRequest::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void BINInitializeRequest::CopyFrom(const BINInitializeRequest& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool BINInitializeRequest::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000003) != 0x00000003) return false;

  return true;
}

void BINInitializeRequest::Swap(BINInitializeRequest* other) {
  if (other != this) {
    std::swap(cp_, other->cp_);
    std::swap(appversion_, other->appversion_);
    std::swap(deviceid_, other->deviceid_);
    std::swap(deviceinfo_, other->deviceinfo_);
    std::swap(country_, other->country_);
    std::swap(language_, other->language_);
    std::swap(pakagename_, other->pakagename_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata BINInitializeRequest::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = BINInitializeRequest_descriptor_;
  metadata.reflection = BINInitializeRequest_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int BINInitializeResponse::kResponseCodeFieldNumber;
const int BINInitializeResponse::kMessageFieldNumber;
const int BINInitializeResponse::kCurrentAppVersionFieldNumber;
const int BINInitializeResponse::kDownloadUrlFieldNumber;
const int BINInitializeResponse::kCashCurrencyFieldNumber;
const int BINInitializeResponse::kGoldCurrencyFieldNumber;
const int BINInitializeResponse::kForceUpdateFieldNumber;
const int BINInitializeResponse::kEnableQuickPlayFieldNumber;
const int BINInitializeResponse::kEnableCashSystemFieldNumber;
const int BINInitializeResponse::kEnablePurchaseCashFieldNumber;
const int BINInitializeResponse::kEnableTopupFieldNumber;
const int BINInitializeResponse::kEnableCashToGoldFieldNumber;
const int BINInitializeResponse::kEnableCashTransferFieldNumber;
const int BINInitializeResponse::kEnableGiftCodeFieldNumber;
const int BINInitializeResponse::kCashToGoldRatioFieldNumber;
const int BINInitializeResponse::kHotlinesFieldNumber;
const int BINInitializeResponse::kFanpageUrlFieldNumber;
const int BINInitializeResponse::kWebsiteUrlFieldNumber;
const int BINInitializeResponse::kEnableGameIdsFieldNumber;
const int BINInitializeResponse::kResetPwSmsSyntaxFieldNumber;
#endif  // !_MSC_VER

BINInitializeResponse::BINInitializeResponse()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void BINInitializeResponse::InitAsDefaultInstance() {
}

BINInitializeResponse::BINInitializeResponse(const BINInitializeResponse& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void BINInitializeResponse::SharedCtor() {
  _cached_size_ = 0;
  responsecode_ = false;
  message_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  currentappversion_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  downloadurl_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  cashcurrency_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  goldcurrency_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  forceupdate_ = false;
  enablequickplay_ = false;
  enablecashsystem_ = false;
  enablepurchasecash_ = false;
  enabletopup_ = false;
  enablecashtogold_ = false;
  enablecashtransfer_ = false;
  enablegiftcode_ = false;
  cashtogoldratio_ = 0;
  fanpageurl_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  websiteurl_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  resetpwsmssyntax_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

BINInitializeResponse::~BINInitializeResponse() {
  SharedDtor();
}

void BINInitializeResponse::SharedDtor() {
  if (message_ != &::google::protobuf::internal::kEmptyString) {
    delete message_;
  }
  if (currentappversion_ != &::google::protobuf::internal::kEmptyString) {
    delete currentappversion_;
  }
  if (downloadurl_ != &::google::protobuf::internal::kEmptyString) {
    delete downloadurl_;
  }
  if (cashcurrency_ != &::google::protobuf::internal::kEmptyString) {
    delete cashcurrency_;
  }
  if (goldcurrency_ != &::google::protobuf::internal::kEmptyString) {
    delete goldcurrency_;
  }
  if (fanpageurl_ != &::google::protobuf::internal::kEmptyString) {
    delete fanpageurl_;
  }
  if (websiteurl_ != &::google::protobuf::internal::kEmptyString) {
    delete websiteurl_;
  }
  if (resetpwsmssyntax_ != &::google::protobuf::internal::kEmptyString) {
    delete resetpwsmssyntax_;
  }
  if (this != default_instance_) {
  }
}

void BINInitializeResponse::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* BINInitializeResponse::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return BINInitializeResponse_descriptor_;
}

const BINInitializeResponse& BINInitializeResponse::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_initialize_2eproto();
  return *default_instance_;
}

BINInitializeResponse* BINInitializeResponse::default_instance_ = NULL;

BINInitializeResponse* BINInitializeResponse::New() const {
  return new BINInitializeResponse;
}

void BINInitializeResponse::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    responsecode_ = false;
    if (has_message()) {
      if (message_ != &::google::protobuf::internal::kEmptyString) {
        message_->clear();
      }
    }
    if (has_currentappversion()) {
      if (currentappversion_ != &::google::protobuf::internal::kEmptyString) {
        currentappversion_->clear();
      }
    }
    if (has_downloadurl()) {
      if (downloadurl_ != &::google::protobuf::internal::kEmptyString) {
        downloadurl_->clear();
      }
    }
    if (has_cashcurrency()) {
      if (cashcurrency_ != &::google::protobuf::internal::kEmptyString) {
        cashcurrency_->clear();
      }
    }
    if (has_goldcurrency()) {
      if (goldcurrency_ != &::google::protobuf::internal::kEmptyString) {
        goldcurrency_->clear();
      }
    }
    forceupdate_ = false;
    enablequickplay_ = false;
  }
  if (_has_bits_[8 / 32] & (0xffu << (8 % 32))) {
    enablecashsystem_ = false;
    enablepurchasecash_ = false;
    enabletopup_ = false;
    enablecashtogold_ = false;
    enablecashtransfer_ = false;
    enablegiftcode_ = false;
    cashtogoldratio_ = 0;
  }
  if (_has_bits_[16 / 32] & (0xffu << (16 % 32))) {
    if (has_fanpageurl()) {
      if (fanpageurl_ != &::google::protobuf::internal::kEmptyString) {
        fanpageurl_->clear();
      }
    }
    if (has_websiteurl()) {
      if (websiteurl_ != &::google::protobuf::internal::kEmptyString) {
        websiteurl_->clear();
      }
    }
    if (has_resetpwsmssyntax()) {
      if (resetpwsmssyntax_ != &::google::protobuf::internal::kEmptyString) {
        resetpwsmssyntax_->clear();
      }
    }
  }
  hotlines_.Clear();
  enablegameids_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool BINInitializeResponse::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required bool responseCode = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &responsecode_)));
          set_has_responsecode();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(18)) goto parse_message;
        break;
      }

      // optional string message = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_message:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_message()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->message().data(), this->message().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(26)) goto parse_currentAppVersion;
        break;
      }

      // optional string currentAppVersion = 3;
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_currentAppVersion:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_currentappversion()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->currentappversion().data(), this->currentappversion().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(34)) goto parse_downloadUrl;
        break;
      }

      // optional string downloadUrl = 4;
      case 4: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_downloadUrl:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_downloadurl()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->downloadurl().data(), this->downloadurl().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(42)) goto parse_cashCurrency;
        break;
      }

      // optional string cashCurrency = 5;
      case 5: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_cashCurrency:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_cashcurrency()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->cashcurrency().data(), this->cashcurrency().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(50)) goto parse_goldCurrency;
        break;
      }

      // optional string goldCurrency = 6;
      case 6: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_goldCurrency:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_goldcurrency()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->goldcurrency().data(), this->goldcurrency().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(56)) goto parse_forceUpdate;
        break;
      }

      // optional bool forceUpdate = 7;
      case 7: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_forceUpdate:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &forceupdate_)));
          set_has_forceupdate();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(64)) goto parse_enableQuickPlay;
        break;
      }

      // optional bool enableQuickPlay = 8;
      case 8: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_enableQuickPlay:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &enablequickplay_)));
          set_has_enablequickplay();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(72)) goto parse_enableCashSystem;
        break;
      }

      // optional bool enableCashSystem = 9;
      case 9: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_enableCashSystem:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &enablecashsystem_)));
          set_has_enablecashsystem();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(80)) goto parse_enablePurchaseCash;
        break;
      }

      // optional bool enablePurchaseCash = 10;
      case 10: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_enablePurchaseCash:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &enablepurchasecash_)));
          set_has_enablepurchasecash();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(88)) goto parse_enableTopup;
        break;
      }

      // optional bool enableTopup = 11;
      case 11: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_enableTopup:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &enabletopup_)));
          set_has_enabletopup();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(96)) goto parse_enableCashToGold;
        break;
      }

      // optional bool enableCashToGold = 12;
      case 12: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_enableCashToGold:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &enablecashtogold_)));
          set_has_enablecashtogold();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(104)) goto parse_enableCashTransfer;
        break;
      }

      // optional bool enableCashTransfer = 13;
      case 13: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_enableCashTransfer:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &enablecashtransfer_)));
          set_has_enablecashtransfer();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(112)) goto parse_enableGiftCode;
        break;
      }

      // optional bool enableGiftCode = 14;
      case 14: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_enableGiftCode:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &enablegiftcode_)));
          set_has_enablegiftcode();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(120)) goto parse_cashToGoldRatio;
        break;
      }

      // optional int32 cashToGoldRatio = 15;
      case 15: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_cashToGoldRatio:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &cashtogoldratio_)));
          set_has_cashtogoldratio();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(130)) goto parse_hotlines;
        break;
      }

      // repeated string hotlines = 16;
      case 16: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_hotlines:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->add_hotlines()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->hotlines(this->hotlines_size() - 1).data(),
            this->hotlines(this->hotlines_size() - 1).length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(130)) goto parse_hotlines;
        if (input->ExpectTag(138)) goto parse_fanpageUrl;
        break;
      }

      // optional string fanpageUrl = 17;
      case 17: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_fanpageUrl:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_fanpageurl()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->fanpageurl().data(), this->fanpageurl().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(146)) goto parse_websiteUrl;
        break;
      }

      // optional string websiteUrl = 18;
      case 18: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_websiteUrl:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_websiteurl()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->websiteurl().data(), this->websiteurl().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(152)) goto parse_enableGameIds;
        break;
      }

      // repeated int32 enableGameIds = 19;
      case 19: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_enableGameIds:
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 2, 152, input, this->mutable_enablegameids())));
        } else if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag)
                   == ::google::protobuf::internal::WireFormatLite::
                      WIRETYPE_LENGTH_DELIMITED) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitiveNoInline<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, this->mutable_enablegameids())));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(152)) goto parse_enableGameIds;
        if (input->ExpectTag(162)) goto parse_resetPwSmsSyntax;
        break;
      }

      // optional string resetPwSmsSyntax = 20;
      case 20: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_resetPwSmsSyntax:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_resetpwsmssyntax()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->resetpwsmssyntax().data(), this->resetpwsmssyntax().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void BINInitializeResponse::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required bool responseCode = 1;
  if (has_responsecode()) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(1, this->responsecode(), output);
  }

  // optional string message = 2;
  if (has_message()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->message().data(), this->message().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      2, this->message(), output);
  }

  // optional string currentAppVersion = 3;
  if (has_currentappversion()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->currentappversion().data(), this->currentappversion().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      3, this->currentappversion(), output);
  }

  // optional string downloadUrl = 4;
  if (has_downloadurl()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->downloadurl().data(), this->downloadurl().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      4, this->downloadurl(), output);
  }

  // optional string cashCurrency = 5;
  if (has_cashcurrency()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->cashcurrency().data(), this->cashcurrency().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      5, this->cashcurrency(), output);
  }

  // optional string goldCurrency = 6;
  if (has_goldcurrency()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->goldcurrency().data(), this->goldcurrency().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      6, this->goldcurrency(), output);
  }

  // optional bool forceUpdate = 7;
  if (has_forceupdate()) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(7, this->forceupdate(), output);
  }

  // optional bool enableQuickPlay = 8;
  if (has_enablequickplay()) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(8, this->enablequickplay(), output);
  }

  // optional bool enableCashSystem = 9;
  if (has_enablecashsystem()) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(9, this->enablecashsystem(), output);
  }

  // optional bool enablePurchaseCash = 10;
  if (has_enablepurchasecash()) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(10, this->enablepurchasecash(), output);
  }

  // optional bool enableTopup = 11;
  if (has_enabletopup()) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(11, this->enabletopup(), output);
  }

  // optional bool enableCashToGold = 12;
  if (has_enablecashtogold()) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(12, this->enablecashtogold(), output);
  }

  // optional bool enableCashTransfer = 13;
  if (has_enablecashtransfer()) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(13, this->enablecashtransfer(), output);
  }

  // optional bool enableGiftCode = 14;
  if (has_enablegiftcode()) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(14, this->enablegiftcode(), output);
  }

  // optional int32 cashToGoldRatio = 15;
  if (has_cashtogoldratio()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(15, this->cashtogoldratio(), output);
  }

  // repeated string hotlines = 16;
  for (int i = 0; i < this->hotlines_size(); i++) {
  ::google::protobuf::internal::WireFormat::VerifyUTF8String(
    this->hotlines(i).data(), this->hotlines(i).length(),
    ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      16, this->hotlines(i), output);
  }

  // optional string fanpageUrl = 17;
  if (has_fanpageurl()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->fanpageurl().data(), this->fanpageurl().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      17, this->fanpageurl(), output);
  }

  // optional string websiteUrl = 18;
  if (has_websiteurl()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->websiteurl().data(), this->websiteurl().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      18, this->websiteurl(), output);
  }

  // repeated int32 enableGameIds = 19;
  for (int i = 0; i < this->enablegameids_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(
      19, this->enablegameids(i), output);
  }

  // optional string resetPwSmsSyntax = 20;
  if (has_resetpwsmssyntax()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->resetpwsmssyntax().data(), this->resetpwsmssyntax().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      20, this->resetpwsmssyntax(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* BINInitializeResponse::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required bool responseCode = 1;
  if (has_responsecode()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(1, this->responsecode(), target);
  }

  // optional string message = 2;
  if (has_message()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->message().data(), this->message().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->message(), target);
  }

  // optional string currentAppVersion = 3;
  if (has_currentappversion()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->currentappversion().data(), this->currentappversion().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->currentappversion(), target);
  }

  // optional string downloadUrl = 4;
  if (has_downloadurl()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->downloadurl().data(), this->downloadurl().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        4, this->downloadurl(), target);
  }

  // optional string cashCurrency = 5;
  if (has_cashcurrency()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->cashcurrency().data(), this->cashcurrency().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        5, this->cashcurrency(), target);
  }

  // optional string goldCurrency = 6;
  if (has_goldcurrency()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->goldcurrency().data(), this->goldcurrency().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        6, this->goldcurrency(), target);
  }

  // optional bool forceUpdate = 7;
  if (has_forceupdate()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(7, this->forceupdate(), target);
  }

  // optional bool enableQuickPlay = 8;
  if (has_enablequickplay()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(8, this->enablequickplay(), target);
  }

  // optional bool enableCashSystem = 9;
  if (has_enablecashsystem()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(9, this->enablecashsystem(), target);
  }

  // optional bool enablePurchaseCash = 10;
  if (has_enablepurchasecash()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(10, this->enablepurchasecash(), target);
  }

  // optional bool enableTopup = 11;
  if (has_enabletopup()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(11, this->enabletopup(), target);
  }

  // optional bool enableCashToGold = 12;
  if (has_enablecashtogold()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(12, this->enablecashtogold(), target);
  }

  // optional bool enableCashTransfer = 13;
  if (has_enablecashtransfer()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(13, this->enablecashtransfer(), target);
  }

  // optional bool enableGiftCode = 14;
  if (has_enablegiftcode()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(14, this->enablegiftcode(), target);
  }

  // optional int32 cashToGoldRatio = 15;
  if (has_cashtogoldratio()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(15, this->cashtogoldratio(), target);
  }

  // repeated string hotlines = 16;
  for (int i = 0; i < this->hotlines_size(); i++) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->hotlines(i).data(), this->hotlines(i).length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target = ::google::protobuf::internal::WireFormatLite::
      WriteStringToArray(16, this->hotlines(i), target);
  }

  // optional string fanpageUrl = 17;
  if (has_fanpageurl()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->fanpageurl().data(), this->fanpageurl().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        17, this->fanpageurl(), target);
  }

  // optional string websiteUrl = 18;
  if (has_websiteurl()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->websiteurl().data(), this->websiteurl().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        18, this->websiteurl(), target);
  }

  // repeated int32 enableGameIds = 19;
  for (int i = 0; i < this->enablegameids_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteInt32ToArray(19, this->enablegameids(i), target);
  }

  // optional string resetPwSmsSyntax = 20;
  if (has_resetpwsmssyntax()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->resetpwsmssyntax().data(), this->resetpwsmssyntax().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        20, this->resetpwsmssyntax(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int BINInitializeResponse::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required bool responseCode = 1;
    if (has_responsecode()) {
      total_size += 1 + 1;
    }

    // optional string message = 2;
    if (has_message()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->message());
    }

    // optional string currentAppVersion = 3;
    if (has_currentappversion()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->currentappversion());
    }

    // optional string downloadUrl = 4;
    if (has_downloadurl()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->downloadurl());
    }

    // optional string cashCurrency = 5;
    if (has_cashcurrency()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->cashcurrency());
    }

    // optional string goldCurrency = 6;
    if (has_goldcurrency()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->goldcurrency());
    }

    // optional bool forceUpdate = 7;
    if (has_forceupdate()) {
      total_size += 1 + 1;
    }

    // optional bool enableQuickPlay = 8;
    if (has_enablequickplay()) {
      total_size += 1 + 1;
    }

  }
  if (_has_bits_[8 / 32] & (0xffu << (8 % 32))) {
    // optional bool enableCashSystem = 9;
    if (has_enablecashsystem()) {
      total_size += 1 + 1;
    }

    // optional bool enablePurchaseCash = 10;
    if (has_enablepurchasecash()) {
      total_size += 1 + 1;
    }

    // optional bool enableTopup = 11;
    if (has_enabletopup()) {
      total_size += 1 + 1;
    }

    // optional bool enableCashToGold = 12;
    if (has_enablecashtogold()) {
      total_size += 1 + 1;
    }

    // optional bool enableCashTransfer = 13;
    if (has_enablecashtransfer()) {
      total_size += 1 + 1;
    }

    // optional bool enableGiftCode = 14;
    if (has_enablegiftcode()) {
      total_size += 1 + 1;
    }

    // optional int32 cashToGoldRatio = 15;
    if (has_cashtogoldratio()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->cashtogoldratio());
    }

  }
  if (_has_bits_[16 / 32] & (0xffu << (16 % 32))) {
    // optional string fanpageUrl = 17;
    if (has_fanpageurl()) {
      total_size += 2 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->fanpageurl());
    }

    // optional string websiteUrl = 18;
    if (has_websiteurl()) {
      total_size += 2 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->websiteurl());
    }

    // optional string resetPwSmsSyntax = 20;
    if (has_resetpwsmssyntax()) {
      total_size += 2 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->resetpwsmssyntax());
    }

  }
  // repeated string hotlines = 16;
  total_size += 2 * this->hotlines_size();
  for (int i = 0; i < this->hotlines_size(); i++) {
    total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
      this->hotlines(i));
  }

  // repeated int32 enableGameIds = 19;
  {
    int data_size = 0;
    for (int i = 0; i < this->enablegameids_size(); i++) {
      data_size += ::google::protobuf::internal::WireFormatLite::
        Int32Size(this->enablegameids(i));
    }
    total_size += 2 * this->enablegameids_size() + data_size;
  }

  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void BINInitializeResponse::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const BINInitializeResponse* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const BINInitializeResponse*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void BINInitializeResponse::MergeFrom(const BINInitializeResponse& from) {
  GOOGLE_CHECK_NE(&from, this);
  hotlines_.MergeFrom(from.hotlines_);
  enablegameids_.MergeFrom(from.enablegameids_);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_responsecode()) {
      set_responsecode(from.responsecode());
    }
    if (from.has_message()) {
      set_message(from.message());
    }
    if (from.has_currentappversion()) {
      set_currentappversion(from.currentappversion());
    }
    if (from.has_downloadurl()) {
      set_downloadurl(from.downloadurl());
    }
    if (from.has_cashcurrency()) {
      set_cashcurrency(from.cashcurrency());
    }
    if (from.has_goldcurrency()) {
      set_goldcurrency(from.goldcurrency());
    }
    if (from.has_forceupdate()) {
      set_forceupdate(from.forceupdate());
    }
    if (from.has_enablequickplay()) {
      set_enablequickplay(from.enablequickplay());
    }
  }
  if (from._has_bits_[8 / 32] & (0xffu << (8 % 32))) {
    if (from.has_enablecashsystem()) {
      set_enablecashsystem(from.enablecashsystem());
    }
    if (from.has_enablepurchasecash()) {
      set_enablepurchasecash(from.enablepurchasecash());
    }
    if (from.has_enabletopup()) {
      set_enabletopup(from.enabletopup());
    }
    if (from.has_enablecashtogold()) {
      set_enablecashtogold(from.enablecashtogold());
    }
    if (from.has_enablecashtransfer()) {
      set_enablecashtransfer(from.enablecashtransfer());
    }
    if (from.has_enablegiftcode()) {
      set_enablegiftcode(from.enablegiftcode());
    }
    if (from.has_cashtogoldratio()) {
      set_cashtogoldratio(from.cashtogoldratio());
    }
  }
  if (from._has_bits_[16 / 32] & (0xffu << (16 % 32))) {
    if (from.has_fanpageurl()) {
      set_fanpageurl(from.fanpageurl());
    }
    if (from.has_websiteurl()) {
      set_websiteurl(from.websiteurl());
    }
    if (from.has_resetpwsmssyntax()) {
      set_resetpwsmssyntax(from.resetpwsmssyntax());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void BINInitializeResponse::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void BINInitializeResponse::CopyFrom(const BINInitializeResponse& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool BINInitializeResponse::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;

  return true;
}

void BINInitializeResponse::Swap(BINInitializeResponse* other) {
  if (other != this) {
    std::swap(responsecode_, other->responsecode_);
    std::swap(message_, other->message_);
    std::swap(currentappversion_, other->currentappversion_);
    std::swap(downloadurl_, other->downloadurl_);
    std::swap(cashcurrency_, other->cashcurrency_);
    std::swap(goldcurrency_, other->goldcurrency_);
    std::swap(forceupdate_, other->forceupdate_);
    std::swap(enablequickplay_, other->enablequickplay_);
    std::swap(enablecashsystem_, other->enablecashsystem_);
    std::swap(enablepurchasecash_, other->enablepurchasecash_);
    std::swap(enabletopup_, other->enabletopup_);
    std::swap(enablecashtogold_, other->enablecashtogold_);
    std::swap(enablecashtransfer_, other->enablecashtransfer_);
    std::swap(enablegiftcode_, other->enablegiftcode_);
    std::swap(cashtogoldratio_, other->cashtogoldratio_);
    hotlines_.Swap(&other->hotlines_);
    std::swap(fanpageurl_, other->fanpageurl_);
    std::swap(websiteurl_, other->websiteurl_);
    enablegameids_.Swap(&other->enablegameids_);
    std::swap(resetpwsmssyntax_, other->resetpwsmssyntax_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata BINInitializeResponse::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = BINInitializeResponse_descriptor_;
  metadata.reflection = BINInitializeResponse_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
